<link rel="stylesheet" href="main.css">

<body class="container_login">
<div class='flex_column'>
  <div class="flex heading_div">
    <img src="images/workos_logo.png" alt="workos logo">
    <div class="heading_text_div">
      <h1>WorkOS</h1>
    </div>
  </div>
  <h2>Java Directory Sync Example App</h2>
  <a class="button login_button" href="/admin_portal/sso">Setup Single Sign On</a>
  <a class="button login_button" href="/admin_portal/dsync">Setup Directory Sync</a>
</div>
</body>