<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<div class="container" style="padding: 40px;">
  <h1>Java Admin Portal Example</h1>

  <a class="btn btn-primary" href="/admin_portal/sso">Setup Single Sign On</a>
  <a class="btn btn-primary" href="/admin_portal/dsync">Setup Directory Sync</a>
</div>
