@param String error

<link rel="stylesheet" href="main.css">

<div class='flex_column container_login'>
    <div class="flex heading_div">
        <img src="images/workos-logo-with-text.png" alt="workos logo">
    </div>
    <h2>Java Directory Sync Example App</h2>
    <div class='flex_column'>
        <div>
            <p>${error}</p>
        </div>
        <div>
            <a href="/logout"><button class="button width-15vw">Go Back</button></a>
        </div>
    </div>
</div>
