@param String error
<link rel="stylesheet" href="main.css">

<body class="container_success">
<div class="logged_in_nav">
    <div class="flex">
        <p>MFA Example Application</p>
    </div>
    <div>
        <img src="images/workos_logo.png" alt="workos logo">
    </div>
</div>
<div class='flex mt-50'>
    <div>
        <img src="/images/blurpy.png" alt="helfplul blurpy">
    </div>
    <div>
        <p>Ope! It's an error.</p>
        <p>${error}</p>

    </div>
</div>
</body>
